pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: ptero-daemon-dev

  # ##TODO## Add Test step with an example config file

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    from: ptero-daemon-dev
    repo: spritsail/pterodactyl-daemon

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]

